# Generated by Django 4.1.2 on 2022-11-24 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advertisements", "0002_advertisement_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="liked",
            field=models.ManyToManyField(
                default=None, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
