# Generated by Django 4.1.2 on 2022-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_tag_alter_article_options_scope_article_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="tags", new_name="scopes",
        ),
        migrations.AddField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
