# Generated by Django 4.1.2 on 2022-10-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_rename_scopes_article_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="tag",),
        migrations.AddField(
            model_name="article",
            name="scopes",
            field=models.ManyToManyField(
                related_name="tag", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
