# Generated by Django 4.1.2 on 2022-10-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_remove_article_tag_article_scopes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="scopes",
            field=models.ManyToManyField(
                related_name="articles", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
