# Generated by Django 4.1.2 on 2022-10-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="teacher",),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(max_length=10, verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(max_length=10, verbose_name="Предмет"),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.teacher"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="school.Membership",
                to="school.teacher",
            ),
        ),
    ]
