# Generated by Django 4.1.3 on 2022-11-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor", old_name="discription", new_name="description",
        ),
    ]
