# Generated by Django 4.1.3 on 2022-11-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0004_rename_sensor_measurement_sensor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement", old_name="sensor_id", new_name="sensor",
        ),
    ]
