# Generated by Django 4.1.2 on 2022-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0002_alter_phone_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone", name="slug", field=models.CharField(max_length=20),
        ),
    ]
